version: '3'
services:
  vuejs-app:
    image: nginx:latest
    container_name: vuejs-container
    ports:
      - "3001:80"
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab-container
    hostname: gitlab.local
    ports:
      - "8443:443"
      - "8081:80"
      - "2222:22"
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:8081'
    restart: unless-stopped